CREATE TRIGGER neighbors_count ON --> CREATE
AFTER COMMIT EXECUTE
UNWIND createdEdges AS createdEdge
WITH startNode(createdEdge) AS start_node
MATCH (start_node)-[*bfs..2]->(end_node)
WITH count(end_node) AS neighbors_count, start_node AS start_node
CALL neighbors.store_count(start_node, neighbors_count) YIELD * RETURN *;
